### ISSUE TITLE
Buttons don't do anything

### ISSUE THREAD

**Issue by patrickomeara** [lepture/markdown-textarea#1]
![image](https://cloud.githubusercontent.com/assets/571773/22532582/281772e0-e93c-11e6-9438-e9a0b57e32de.png)

I can get this up and running, but the buttons don't do anything, am I missing something?

**Comment by lepture** [comment]
@patrickomeara Chrome 53+ has disabled `document.createEvent`.

I'm rewriting this.

**Comment by patrickomeara** [comment]
Cool, let me know if you need any help

**Comment by lepture** [comment]
@patrickomeara It should be working now if you upgrade the dependency of selection.js
